Reapply "模拟算法逻辑得到结果1.0"
135ljh/RiskIdentificationSystem pull request #2
Opened 2024-07-30 16:58 UTC by 135ljh

This reverts commit 7697255ab95e1a2291788c537039f4baa73cf260.

2024-07-30 16:59 UTC, 135ljh commented
@suyiiyii

2024-07-30 17:01 UTC, 135ljh commented
@suyiiyii

2024-07-30 17:05 UTC, suyiiyii reviewed
WIP

2024-07-30 17:05 UTC, suyiiyii commented on Main/src/main/java/com/ljh/main/ScopeTask/Service/Identify.java
这里建议把生产者消费者拆开，放到不同的文件下面，没必要全部挤在一个文件里面

2024-07-30 17:16 UTC, suyiiyii requested changes

2024-07-30 17:16 UTC, suyiiyii commented on Main/src/main/java/com/ljh/main/ScopeTask/Dto/ResultDto.java
> +    private String username;
这里不要给前端返回多余的字段

2024-07-30 17:16 UTC, suyiiyii commented on Main/src/main/java/com/ljh/main/ScopeTask/Service/Identify.java
> +    private final List<String> lines = new ArrayList<>();
这里建议用一个阻塞队列，因为多线程环境，要考虑线程安全问题了

2024-07-30 17:16 UTC, suyiiyii commented on Main/src/main/java/com/ljh/main/ScopeTask/Service/Identify.java
> +class Producer extends Thread {
生产者直接整合进service层中，向队列中添加任务就行了

2024-07-30 18:08 UTC, suyiiyii requested changes
加油，按照要求改就行了，有不懂的就 `reply`

2024-07-30 18:08 UTC, suyiiyii commented on Main/web/WEB-INF/web.xml
> +<?xml version="1.0" encoding="UTF-8"?>
这个文件是做啥的

2024-07-30 18:08 UTC, suyiiyii commented on Main/src/main/java/com/ljh/main/ScopeTask/Service/CreateTextTaskService.java
> +    public CreateTextTaskService(TaskMapper taskMapper, ResultMapper resultMapper) {
这里，类名建议用名词，而不是动词短语

2024-07-30 18:08 UTC, suyiiyii commented on Main/src/main/java/com/ljh/main/ScopeTask/Service/CreateTextTaskService.java
> +                Identify identify = new Identify();
生产者消费者模型中的队列不能在service里面创建，可能要了解一下spring的生命周期管理

2024-07-30 18:08 UTC, suyiiyii commented on Main/src/main/java/com/ljh/main/ScopeTask/Service/CreateTextTaskService.java
> +                taskMapper.updateTaskStatus(taskDto.getTaskId(),"已完成",taskDto.getUsername());
应该在消费者处理完了再更新状态，
另，建议分清楚entity和dto

2024-07-30 18:08 UTC, suyiiyii commented on Main/src/main/java/com/ljh/main/ScopeTask/Service/CreateTextTaskService.java
>                  return ResponseEntity.ok(map);
返回数据先定义好数据模型，参考接口文档

2024-07-30 18:08 UTC, suyiiyii commented on Main/src/main/java/com/ljh/main/ScopeTask/Service/Identify.java
> +        String pythexeonpath= "C:\\Users\\13530\\AppData\\Local\\Microsoft\\WindowsApps\\python.exe";
这里可以把具体的执行脚本的逻辑提取出来，方便测试

2024-07-31 12:51 UTC, suyiiyii commented on Main/src/main/java/com/ljh/main/ScopeTask/ProducerConsumerModel/Consumer.java
> +          BufferedReader in = new BufferedReader(new InputStreamReader(pr.getInputStream(), "UTF-8")); // 使用UTF-8编码
传参好像走的是命令参数，不是标准输入

2024-08-01 13:20 UTC, suyiiyii commented
写了个测试用例，你康康能不能跑了
https://app.apifox.com/link/project/4841573/api-test/scenario-4812155?branchId=4496743 提交任务

2024-08-01 16:34 UTC, suyiiyii commented on Main/src/test/java/com/ljh/main/MainApplicationTests.java
> +        String pythonscriptpath= "C:\\code\\RiskIdentificationSystem\\Main\\mock.py";
脚本路径改为相对路径，python路径改为`python3`

2024-08-01 17:16 UTC, merged